### ISSUE TITLE
[Question] 本地启动 Unhandled Runtime Error

### ISSUE THREAD

**Issue by Trilingual-byford** [perfect-panel/ppanel-web#4]
### 🧐 问题描述 | Proposed Solution

I followed the the following instructions
https://github.com/perfect-panel/ppanel-web/tree/main
 ---
git clone https://github.com/perfect-panel/ppanel-web.git
cd ppanel-web

# Install dependencies
pnpm install
---

When I am trying to open the http://localhost:3000/ on my local machine
I encountered the following error
---
/opt/homebrew/bin/pnpm run dev

> ppanel-admin-web@ dev /Users/nightfurukawa/Documents/ppanel-web/apps/admin
> next dev --turbopack

   ▲ Next.js 15.0.3 (Turbopack)
   - Local:        http://localhost:3000
   - Experiments (use with caution):
     · turbo

 ✓ Starting...
 ✓ Ready in 654ms
 ○ Compiling / ...

warn - The class `delay-[var(--delay)]` is ambiguous and matches multiple utilities.
warn - If this is content and not a class, replace it with `delay-&lsqb;var(--delay)&rsqb;` to silence this warning.

warn - The class `duration-[var(--transition-length)]` is ambiguous and matches multiple utilities.
warn - If this is content and not a class, replace it with `duration-&lsqb;var(--transition-length)&rsqb;` to silence this warning.
 ✓ Compiled / in 3.9s
 ⨯ TypeError: Invalid URL
    at dispatchHttpRequest (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2878:24)
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2807:9
    at new Promise (<anonymous>)
    at wrapAsync (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2791:12)
    at http (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2824:12)
    at Axios.dispatchRequest (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4020:12)
    at async Axios.request (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4088:20)
    at async Module.generateMetadata (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[root of the server]__34b209._.js:4208:20)
    at Axios.request (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4092:49)
    at async Module.generateMetadata (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[root of the server]__34b209._.js:4208:20)
digest: "1824754634"
 ⨯ TypeError: Invalid URL
    at dispatchHttpRequest (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2878:24)
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2807:9
    at new Promise (<anonymous>)
    at wrapAsync (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2791:12)
    at http (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:2824:12)
    at Axios.dispatchRequest (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4020:12)
    at async Axios.request (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4088:20)
    at async Module.generateMetadata (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[root of the server]__34b209._.js:4208:20)
    at Axios.request (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4f502_axios_lib_77cfbd._.js:4092:49)
    at async Module.generateMetadata (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[root of the server]__34b209._.js:4208:20)
digest: "1824754634"
 ⨯ ReferenceError: document is not defined
    at createTag (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:29:9)
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1238:26
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1245:10
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1424:6
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/packages/ui/src/lotties/index.tsx [app-ssr] (ecmascript) (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[project]_packages_ui_src_lotties_25051c._.js:57:354)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/apps/admin/app/(auth)/page.tsx [app-ssr] (ecmascript) (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[project]_apps_admin_375663._.js:2025:146)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at commonJsRequire (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:147:20)
digest: "870897063"
 ⨯ ReferenceError: document is not defined
    at createTag (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:29:9)
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1238:26
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1245:10
    at /Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/4766f_lottie-web_build_player_lottie_f0cb54.js:1424:6
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/packages/ui/src/lotties/index.tsx [app-ssr] (ecmascript) (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[project]_packages_ui_src_lotties_25051c._.js:57:354)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/apps/admin/app/(auth)/page.tsx [app-ssr] (ecmascript) (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[project]_apps_admin_375663._.js:2025:146)
    at instantiateModule (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at commonJsRequire (/Users/nightfurukawa/Documents/ppanel-web/apps/admin/.next/server/chunks/ssr/[turbopack]_runtime.js:147:20)
digest: "870897063"
 GET / 500 in 740ms
---

I am using a MacBook Pro.
Macos SeQuoia 15.1.1 (24B91)
pnpm 9.12.3

**Comment by IMZCC** [comment]
This is a problem with the main branch, but not with the develop branch.
